%----------------------------------------------------------------------
% filename: create_group_train_test_csv_files.m
% author: rbd
% 5/11/21 
% descr: auto create train and test extracted from tables
% Run #52A 
%---------------------------------------------------------------------
% Test 
B = {'USDAS142','USDAS143','USDAS144','USDAS145','USDAS146', ...
     'USDAS147','USDAS148','USDAS152','USDAS156','USDAS160', ...
     'USDAS172','USDAS176','USDAS051','USDAS281','USDAS033', ...
     'USDAS237','USDAS265','USDAS057','USDAS253','USDAS245', ...
     'USDAS277','USDAS082','USDAS083','USDAS084','USDAS085', ...
     'USDAS086','USDAS087','USDAS088','USDAS089','USDAS090', ...
     'USDAS091','USDAS105','USDAS166','USDAS178', ...
     'USDAS161','USDAS162',...
     'USDAS185','USDAS193','USDAS201','USDAS205','USDAS209', ...
     'USDAS215','USDAS217','USDAS221','USDAS225','USDAS229', ...
     'USDAS249','USDAS253','USDAS261','USDAS257','USDAS273'
     };
 
 % Train to be grouped
C = {'USDAS135','USDAS128','USDAS121', ...
     'USDAS122','USDAS129','USDAS136', ...
     'USDAS123','USDAS130','USDAS137', ...
     'USDAS124','USDAS131','USDAS138', ...
     'USDAS125','USDAS132','USDAS139', ...
     'USDAS126','USDAS133','USDAS140', ...
     'USDAS127','USDAS134','USDAS141', ...
     'USDAS149','USDAS150','USDAS151', ...
     'USDAS153','USDAS154','USDAS155', ...
     'USDAS157','USDAS158','USDAS159', ...
     'USDAS169','USDAS170','USDAS171', ...
     'USDAS173','USDAS174','USDAS175', ...
     'USDAS031','USDAS041','USDAS241', ...
     'USDAS282','USDAS283','USDAS284', ...
     'USDAS263','USDAS263','USDAS264', ...    
     'USDAS238','USDAS239','USDAS240', ...
     'USDAS266','USDAS267','USDAS268', ...
     'USDAS047','USDAS047','USDAS037', ...
     'USDAS254','USDAS255','USDAS256', ...
     'USDAS246','USDAS247','USDAS248', ...    
     'USDAS278','USDAS279','USDAS280', ...
     'USDAS072','USDAS072','USDAS062', ...
     'USDAS073','USDAS073','USDAS063', ...
     'USDAS074','USDAS074','USDAS064', ...
     'USDAS075','USDAS075','USDAS065', ...   
     'USDAS076','USDAS076','USDAS066', ...
     'USDAS077','USDAS077','USDAS067', ...
     'USDAS078','USDAS078','USDAS068', ...
     'USDAS079','USDAS079','USDAS069', ...
     'USDAS070','USDAS080','USDAS189', ...   
     'USDAS092','USDAS093','USDAS098', ...
     'USDAS094','USDAS106','USDAS107', ...
     'USDAS165','USDAS167','USDAS168', ...
     'USDAS177','USDAS179','USDAS180', ...
     'USDAS164','USDAS164','USDAS184', ...
     'USDAS163','USDAS163','USDAS183', ...
     'USDAS186','USDAS187','USDAS188', ...
     'USDAS194','USDAS195','USDAS196', ...
     'USDAS202','USDAS203','USDAS204', ...
     'USDAS206','USDAS207','USDAS208', ...
     'USDAS210','USDAS211','USDAS212', ...
     'USDAS216','USDAS216','USDAS216', ...
     'USDAS218','USDAS219','USDAS220', ...
     'USDAS222','USDAS223','USDAS224', ...
     'USDAS226','USDAS227','USDAS228', ...
     'USDAS230','USDAS231','USDAS232', ...
     'USDAS250','USDAS251','USDAS252', ...
     'USDAS254','USDAS255','USDAS256', ...
     'USDAS262','USDAS262','USDAS262', ...
     'USDAS258','USDAS259','USDAS260', ...
     'USDAS274','USDAS275','USDAS276'}; % Note repeated 'USDAS184' & 'USDAS183'

  group                     =  3;

  num_classes = 51;
  num_fish = 51; 
         
  fish_value = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...
                 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 ...
                 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 ...
                 46 47 48 49 50 51];

  fish_name = char('coho salmon''chinook_salmon',...
                   'sockeye_salmon','rock_fish',...
                   'pacific_halibut','pacific_cod',...
                   'sablefish','yellow_eye_rockfish',...
                   'calif_flounder','opah');
                   
  M = containers.Map(B,fish_value); 
%-------------------------------------------------------------------------
% Training              Training             Training            
%-------------------------------------------------------------------------
 
%----------------------
% Train Vis Load Table
%----------------------
load('../source_tables/tbl_vis.mat');
T                         = tbl_vis;
dir_data_file             =  '../All_VS/VS_Train';
dir_loc_file              =  '../All_VS/VS_Loc_Train';
dir_count_file            =  '../All_VS';
count_file_name           =  'vs_train_count';
spectra_low_col           = 10;
spectra_high_col          = 134;
flag_loc                  = 0;

norm                      = 0;


[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm,flag_loc);
               
disp('Done with VS Train Processing');

%----------------------
% Train IR Load Table
%----------------------
load('../source_tables/tbl_SWIR.mat');
T                         = tbl_SWIR;
dir_data_file             =  '../All_IR/IR_Train';
dir_loc_file              =  '../All_IR/IR_Loc_Train';
dir_count_file            =  '../All_IR';
count_file_name           =  'ir_train_count';
spectra_low_col           = 10;
spectra_high_col          = 125;
flag_loc                  = 0;

norm                      = 0;

[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm,flag_loc);

disp('Done with IR  Train Processing');

%----------------------
% Train FL Load Table
%----------------------
load('../source_tables/tbl_FL.mat');
T                         = tbl_FL;
dir_data_file             =  '../All_FL/FL_Train';
dir_loc_file              =  '../All_FL/FL_Loc_Train';
dir_count_file            =  '../All_FL';
count_file_name           =  'fl_train_count';
spectra_low_col           = 10;
spectra_high_col          = 69;
flag_loc                  = 0;

norm                      = 1;

[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm,flag_loc);
               
disp('Done with FL Train Processing');
               
debug = 1;

%-------------------------------------------------------------------------
% Testing              Testing             Testing            
%-------------------------------------------------------------------------

%----------------------
% Test Vis Load Table
%----------------------
load('../source_tables/tbl_vis.mat');
T                         = tbl_vis;
dir_data_file             =  '../All_VS/VS_Test';
dir_loc_file              =  '../All_VS/VS_Loc_Test';
dir_count_file            =  '../All_VS';
count_file_name           =  'vs_test_count';
spectra_low_col           = 10;
spectra_high_col          = 134;
flag_loc                  = 1;

norm                      = 0;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm,flag_loc);
               
disp('Done with VS Test Processing');

debug = 1;

%----------------------
% Test IR Load Table
%----------------------
load('../source_tables/tbl_SWIR.mat');
T                         = tbl_SWIR;
dir_data_file             =  '../All_IR/IR_Test';
dir_loc_file              =  '../All_IR/IR_Loc_Test';
dir_count_file            =  '../All_IR';
count_file_name           =  'ir_test_count';
spectra_low_col           = 10;
spectra_high_col          = 125;
flag_loc                  = 1;

norm                      = 0;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm,flag_loc);
               
disp('Done with IR Test Processing');

debug = 1;

%----------------------
% Test FL Load Table
%----------------------
load('../source_tables/tbl_FL.mat');
T                         = tbl_FL;
dir_data_file             =  '../All_FL/FL_Test';
dir_loc_file              =  '../All_FL/FL_Loc_Test';
dir_count_file            =  '../All_FL';
count_file_name           =  'fl_test_count';
spectra_low_col           = 10;
spectra_high_col          = 69;
flag_loc                  = 1;

norm                      = 1;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_loc_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm,flag_loc);
               
disp('Done with FL Test Processing');

debug = 1;
               
