%----------------------------------------------------------------------
% filename: create_group_train_test_csv_files.m
% author: rbd
% 4/18/21 
% descr: auto create train and test extracted from tables
% Run #46C 
%---------------------------------------------------------------------
% Test 
B = {'USDAS128','USDAS129','USDAS130','USDAS131','USDAS132', ...
     'USDAS133','USDAS134','USDAS150','USDAS154','USDAS158', ...
     'USDAS170','USDAS174','USDAS051','USDAS052','USDAS053', ...
     'USDAS055','USDAS056','USDAS057','USDAS058','USDAS060', ...
     'USDAS081','USDAS082','USDAS083','USDAS084','USDAS085', ...
     'USDAS086','USDAS087','USDAS088','USDAS089','USDAS090', ...
     'USDAS102','USDAS105','USDAS166','USDAS178', ...
     'USDAS161','USDAS162',...
     'USDAS187','USDAS195','USDAS203','USDAS207','USDAS211' ...
     'USDAS216','USDAS219','USDAS223','USDAS227','USDAS229'};
 
 % Train to be grouped
C = {'USDAS142','USDAS121','USDAS135', ...
     'USDAS143','USDAS136','USDAS122', ...
     'USDAS144','USDAS137','USDAS123', ...
     'USDAS145','USDAS138','USDAS124', ...
     'USDAS146','USDAS139','USDAS125', ...
     'USDAS147','USDAS140','USDAS126', ...
     'USDAS148','USDAS141','USDAS127', ...
     'USDAS152','USDAS151','USDAS149', ...
     'USDAS156','USDAS155','USDAS153', ...
     'USDAS160','USDAS159','USDAS157', ...
     'USDAS172','USDAS171','USDAS169', ...
     'USDAS176','USDAS175','USDAS173', ...
     'USDAS031','USDAS031','USDAS041', ...
     'USDAS032','USDAS032','USDAS042', ...
     'USDAS033','USDAS033','USDAS043', ...    
     'USDAS035','USDAS035','USDAS045', ...
     'USDAS036','USDAS036','USDAS046', ...
     'USDAS037','USDAS037','USDAS047', ...
     'USDAS038','USDAS038','USDAS048', ...
     'USDAS040','USDAS040','USDAS050', ...    
     'USDAS061','USDAS061','USDAS071', ...
     'USDAS062','USDAS062','USDAS072', ...
     'USDAS063','USDAS063','USDAS073', ...
     'USDAS064','USDAS064','USDAS074', ...
     'USDAS065','USDAS065','USDAS075', ...   
     'USDAS066','USDAS066','USDAS076', ...
     'USDAS067','USDAS067','USDAS077', ...
     'USDAS068','USDAS068','USDAS078', ...
     'USDAS069','USDAS069','USDAS079', ...
     'USDAS070','USDAS070','USDAS080', ...   
     'USDAS098','USDAS098','USDAS101', ...
     'USDAS094','USDAS094','USDAS106', ...
     'USDAS165','USDAS165','USDAS167', ...
     'USDAS177','USDAS177','USDAS179', ...
     'USDAS184','USDAS184','USDAS164', ...
     'USDAS183','USDAS183','USDAS163', ...
     'USDAS185','USDAS188','USDAS186', ...
     'USDAS193','USDAS196','USDAS194', ...
     'USDAS201','USDAS204','USDAS202', ...
     'USDAS205','USDAS208','USDAS206', ...
     'USDAS209','USDAS212','USDAS210', ...
     'USDAS215','USDAS215','USDAS215', ...
     'USDAS217','USDAS220','USDAS218', ...
     'USDAS221','USDAS224','USDAS222', ...
     'USDAS225','USDAS228','USDAS226', ...
     'USDAS231','USDAS231','USDAS230'}; % Note repeated 'USDAS184' & 'USDAS183'

 group                     =  3;

 
  num_fish = 46; 
         
  fish_value = [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...
                 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 ...
                 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 ...
                 46];

  fish_name = char('coho salmon''chinook_salmon',...
                   'sockeye_salmon','rock_fish',...
                   'pacific_halibut','pacific_cod',...
                   'sablefish','yellow_eye_rockfish',...
                   'calif_flounder','opah');
                   
  M = containers.Map(B,fish_value); 
%-------------------------------------------------------------------------
% Training              Training             Training            
%-------------------------------------------------------------------------
 
%----------------------
% Train Vis Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_vis.mat');
T                         = tbl_vis;
dir_data_file             =  '../All_VS/VS_Train';
dir_count_file            =  '../All_VS';
count_file_name           =  'vs_train_count';
spectra_low_col           = 10;
spectra_high_col          = 134;

norm                      = 0;


[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm);
               
disp('Done with VS Train Processing');

%----------------------
% Train IR Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_SWIR.mat');
T                         = tbl_SWIR;
dir_data_file             =  '../All_IR/IR_Train';
dir_count_file            =  '../All_IR';
count_file_name           =  'ir_train_count';
spectra_low_col           = 10;
spectra_high_col          = 125;

norm                      = 0;

[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm);

disp('Done with IR  Train Processing');

%----------------------
% Train FL Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_FL.mat');
T                         = tbl_Fluorescence;
dir_data_file             =  '../All_FL/FL_Train';
dir_count_file            =  '../All_FL';
count_file_name           =  'fl_train_count';
spectra_low_col           = 10;
spectra_high_col          = 69;

norm                      = 1;

[ done] = create_group_train_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,C,spectra_low_col,spectra_high_col,group,norm);
               
disp('Done with FL Train Processing');
               
debug = 1;

%-------------------------------------------------------------------------
% Testing              Testing             Testing            
%-------------------------------------------------------------------------

%----------------------
% Test Vis Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_vis.mat');
T                         = tbl_vis;
dir_data_file             =  '../All_VS/VS_Test';
dir_count_file            =  '../All_VS';
count_file_name           =  'vs_test_count';
spectra_low_col           = 10;
spectra_high_col          = 134;

norm                      = 0;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm);
               
disp('Done with VS Test Processing');

debug = 1;

%----------------------
% Test IR Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_SWIR.mat');
T                         = tbl_SWIR;
dir_data_file             =  '../All_IR/IR_Test';
dir_count_file            =  '../All_IR';
count_file_name           =  'ir_test_count';
spectra_low_col           = 10;
spectra_high_col          = 125;

norm                      = 0;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm);
               
disp('Done with IR Test Processing');

debug = 1;

%----------------------
% Test FL Load Table
%----------------------
load('../table_pantea_46_fish_20210406/tbl_FL.mat');
T                         = tbl_Fluorescence;
dir_data_file             =  '../All_FL/FL_Test';
dir_count_file            =  '../All_FL';
count_file_name           =  'fl_test_count';
spectra_low_col           = 10;
spectra_high_col          = 69;

norm                      = 1;

[ done] = create_test_csv_files_func(T,...
                   dir_data_file,dir_count_file,count_file_name,...
                   B,spectra_low_col,spectra_high_col,norm);
               
disp('Done with FL Test Processing');

debug = 1;
               
